version: 2
updates:
  # For Cargo (Rust) dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"

  # For GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

