[package]
name = "aoc2024_rs"
version = "0.1.0"
edition = "2021"

[dependencies]
ordered-float = "4.5.0"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
rustworkx-core = "0.15.1"
