[package]
name = "aoc-2025"
edition.workspace = true
version.workspace = true

[lib]
name = "aoc2025"
path = "src/lib.rs"

[dependencies]
aoc-common = { path = "../aoc-common" }
anyhow.workspace = true
